package com.mghelas.internship_playground.storage.entity;

import com.j256.ormlite.field.DatabaseField;

public class SweetIngredient {
    public final static String SWEET_ID_FIELD_NAME = "sweet_id";
    public final static String INGREDIENT_ID_FIELD_NAME = "ingredient_id";

    /**
     * This id is generated by the database and set on the object when it is passed to the create method. An id is
     * needed in case we need to update or delete this object in the future.
     */
    @DatabaseField(generatedId = true)
    int id;

    @DatabaseField(foreign = true, columnName = INGREDIENT_ID_FIELD_NAME)
    Sweet sweet;

    @DatabaseField(foreign = true, columnName = INGREDIENT_ID_FIELD_NAME)
    Ingredient ingredient;

    public SweetIngredient() {
    }

    public SweetIngredient(Sweet sweet, Ingredient ingredient) {
        this.sweet = sweet;
        this.ingredient = ingredient;
    }
}
